//
// Created by Boaretti on 8/31/2020.
//

#ifndef UNTITLED_MOTOR_MOTION_DEFINITIONS_H
#define UNTITLED_MOTOR_MOTION_DEFINITIONS_H

#define LOW 0
#define HIGH 1

//STEPS DEFINITION
const int BASE_STEPS = 200;
//X
const int MOTOR_X_SPEED_RPM = 900;
const int MOTOR_X_MODE_FACTOR  = 4;  // full step
inline int MOTOR_X_STEPS_REV() {return (BASE_STEPS * MOTOR_X_MODE_FACTOR );}

//Y
const int MOTOR_Y_SPEED_RPM = 240;
const int MOTOR_Y_MODE_FACTOR = 4; // full step
inline int MOTOR_Y_STEPS_REV() {return (BASE_STEPS * MOTOR_Y_MODE_FACTOR );}

//RAMP DEFINITION
//IT DEFINES THE TIME (RAMP_TIME_S) TO REACH THE MAX SPEED
//RAMP_LEVELS_N DEFINES NUMBER OF EVALUATION TO BE DONE, HIGH VALUES GENERATE SMOOTH ACCELERATION
//

const int  RAMP_TIME_S  = 1;
const int  RAMP_LEVELS_N = 100;

const long ONE_SECOND_US = 1000000;

const int PULLEY_THEETH_N = 20;
const int PULLEY_PITCH_MM = 2;
const int STEPS_REVOLUTION = MOTOR_X_STEPS_REV();

const int COLUMN_PITCH_MM = 60;
const int ROW_PITCH_MM = 47;


inline int STEPS_FOR_MM(){ return ( STEPS_REVOLUTION / ( PULLEY_THEETH_N * PULLEY_PITCH_MM ) );}

#endif //UNTITLED_MOTOR_MOTION_DEFINITIONS_H
