//
// Created by Boaretti on 8/31/2020.
//

#ifndef UNTITLED_STEP_MOTORS_PIN_DEFINITIONS_H
#define UNTITLED_STEP_MOTORS_PIN_DEFINITIONS_H

#define X_AXIS_HOME_PIN 110
#define Y_AXIS_HOME_PIN 111

//CONVENTION
#define MOTOR_DISABLED 0 // enable motor w/ 0
#define MOTOR_ENABLED 1

//PIN DEFINITIONS FOR MOTOR_X
#define MOTOR_X_ENABLE_PIN 57 // GPIO1_25 - YELLOW WIRE
#define MOTOR_X_STEP_PIN 49   // GPIO1_17 - WHITE WIRE
#define MOTOR_X_DIR_PIN 116   // GPIO3_20 - WHITE-GREEN WIRE
#define MOTOR_X_FAULT_PIN 0

//PIN DEFINITIONS FOR MOTOR_Y
#define MOTOR_Y_ENABLE_PIN 98 // GPIO3_2 - YELLOW WIRE
#define MOTOR_Y_STEP_PIN 97   // GPIO3_11 - WHITE WIRE
#define MOTOR_Y_DIR_PIN 66   // GPIO2_2 - WHITE-GREEN WIRE
#define MOTOR_Y_FAULT_PIN 0

#define GPIO_OUTPUT 1
#define GPIO_INPUT 0

#define LOW 0
#define HIGH 1

#define MOTOR_DISABLED 0 // enable motor w/ 0
#define MOTOR_ENABLED 1


#endif //UNTITLED_STEP_MOTORS_PIN_DEFINITIONS_H
